### ISSUE TITLE
just rethink a little bit , there is simple solution instead of for

### ISSUE THREAD

**Issue by moatasemelsayed** [Amr1Wahba/Embedded-Linux-Team-E1#3]
https://github.com/Amr1Wahba/Embedded-Linux-Team-E1/blob/c49772bc00a787b72214883816a7d2477ad39493/Python%20Tasks%20Team/Kerolos%20Mikhail/01/Vowel_Not.py#L8

**Comment by Kerolos-Mikhail** [comment]
Thanks for feedback
I updated the solution
